const puppeteer=require('/Users/annserputko/Desktop/штаб/_Технічне/chrome-mcp-server/node_modules/puppeteer-core');
const CHROME='/Users/annserputko/.cache/puppeteer/chrome/mac_arm-127.0.6533.88/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
const fs=require('fs'); const sleep=ms=>new Promise(r=>setTimeout(r,ms)); const R={};
setTimeout(()=>{fs.writeFileSync('_build/qa_live.json',JSON.stringify(R,null,1));console.log('TIMEOUT-partial');process.exit(2)},170000);
(async()=>{
const b=await puppeteer.launch({executablePath:CHROME,headless:'new',args:['--no-sandbox','--hide-scrollbars','--disable-dev-shm-usage']});
const p=await b.newPage();
await p.setUserAgent('Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1');
await p.setViewport({width:390,height:844,deviceScaleFactor:2,isMobile:true,hasTouch:true});
const net=[]; p.on('response',r=>{try{net.push({u:r.url(),len:+(r.headers()['content-length']||0)})}catch(e){}});
// 1) HOME: cookie banner + header promise + floating icon
await p.goto('https://selvaro.de/',{waitUntil:'domcontentloaded',timeout:45000}); await sleep(4000);
R.c1_cookie=await p.evaluate(()=>{const els=[...document.querySelectorAll('div,section,aside')].filter(e=>{const r=e.getBoundingClientRect(),cs=getComputedStyle(e);return r.height>innerHeight*0.55&&r.width>innerWidth*0.8&&['fixed','absolute'].includes(cs.position)&&cs.visibility!=='hidden'&&+cs.opacity>0.5&&/cookie|consent|privacy|datenschutz/i.test((e.className||'')+' '+(e.id||'')+' '+e.innerText.slice(0,300))});const top=document.elementFromPoint(195,420);const heroBtn=[...document.querySelectorAll('a,button')].find(a=>/entdecken|shop|kaufen/i.test(a.innerText));let blocked=null;if(heroBtn){const r=heroBtn.getBoundingClientRect();if(r.width>0){const at=document.elementFromPoint(r.x+r.width/2,Math.max(5,Math.min(innerHeight-5,r.y+r.height/2)));blocked=at?!(at===heroBtn||heroBtn.contains(at)):null}}
 return {fullscreenOverlays:els.length,overlayH:els[0]?Math.round(els[0].getBoundingClientRect().height):null,viewportH:innerHeight,topElAtCenter:top?(top.tagName+'.'+String(top.className).slice(0,40)):null,heroCtaBlocked:blocked}});
R.c6_header=await p.evaluate(()=>{const h=document.querySelector('header');const t=h?h.innerText.replace(/\s+/g,' ').trim():null;const ann=document.querySelector('[class*="announcement"],[class*="topbar"],[class*="top-bar"],[class*="marquee"]');return {headerText:t?t.slice(0,200):null,shippingWord:/versand|lieferung|rückgabe|garantie|kostenlos/i.test(t||''),announcementText:ann?ann.innerText.replace(/\s+/g,' ').trim().slice(0,160):null}});
R.c9_floatingIcon=await p.evaluate(()=>{const f=[...document.querySelectorAll('button,div,a')].filter(e=>{const r=e.getBoundingClientRect(),cs=getComputedStyle(e);return cs.position==='fixed'&&r.width>18&&r.width<90&&r.height<90&&r.bottom>0&&r.top<innerHeight&&/cookie|consent|einstellung|pandectes/i.test((e.className||'')+(e.id||'')+(e.getAttribute('aria-label')||''))});return f.map(e=>{const r=e.getBoundingClientRect();const under=document.elementsFromPoint(Math.min(389,Math.max(1,r.x+r.width/2)),Math.min(843,Math.max(1,r.y+r.height/2))).slice(1,3).map(x=>x.tagName+'.'+String(x.className).slice(0,30));return {cls:String(e.className).slice(0,50),x:Math.round(r.x),y:Math.round(r.y),w:Math.round(r.width),h:Math.round(r.height),under}})});
R.c8_payment_home=await p.evaluate(()=>{const f=document.querySelector('footer');return {footerImgs:f?f.querySelectorAll('img,svg').length:null,payWords:/visa|mastercard|paypal|klarna|apple pay|google pay/i.test(document.body.innerText)}});
R.c10_footer=await p.evaluate(()=>{const f=document.querySelector('footer');if(!f)return null;const links=[...f.querySelectorAll('a')].map(a=>({t:a.innerText.trim().slice(0,40),href:a.getAttribute('href')}));const wa=f.innerText.match(/WhatsApp[^\n]{0,40}/i);return {whatsappLine:wa?wa[0]:null,whatsappLink:links.find(l=>/whatsapp/i.test(l.t)||/wa\.me|whatsapp/i.test(l.href||'')),rueckgabe:links.filter(l=>/rückgabe|garantie|retour/i.test(l.t)),totalLinks:links.length}});
// 2) PDP
net.length=0;
await p.goto('https://selvaro.de/products/lernturm-klappbar',{waitUntil:'domcontentloaded',timeout:45000}); await sleep(6000);
R.c2_gif=(()=>{const big=net.filter(x=>x.len>1e6).sort((a,b)=>b.len-a.len).slice(0,5).map(x=>({KB:Math.round(x.len/1024),u:x.u.slice(0,110)}));return {biggest:big,totalKB:Math.round(net.reduce((a,x)=>a+x.len,0)/1024)}})();
R.c3_atc=await p.evaluate(async()=>{const sl=ms=>new Promise(r=>setTimeout(r,ms));const find=()=>[...document.querySelectorAll('button,a,input[type=submit]')].filter(e=>/warenkorb|kaufen|in den korb|add to cart/i.test(e.innerText||e.value||''));const main=find()[0];const mb=main?main.getBoundingClientRect().bottom+scrollY:null;const target=Math.round((mb||900)+innerHeight*1.5);for(let y=0;y<=target;y+=400){scrollTo(0,y);await sl(80)}scrollTo(0,target);await sl(1200);const vis=find().filter(e=>{const r=e.getBoundingClientRect();return r.width>30&&r.bottom>0&&r.top<innerHeight});const pinned=vis.filter(e=>{for(let x=e;x&&x!==document.documentElement;x=x.parentElement){const ps=getComputedStyle(x).position;if(ps==='fixed'||ps==='sticky')return true}return false});return {mainAtcBottomPx:mb?Math.round(mb):null,scrolledTo:Math.round(scrollY),docH:document.documentElement.scrollHeight,visibleAtc:vis.length,pinnedAtc:pinned.length}});
R.c7_reviews=await p.evaluate(()=>{const t=document.body.innerText;const m=t.match(/\(?\s*0\s*Bewertung(en)?\s*\)?/i);const any=t.match(/\d+\s*Bewertung(en)?/i);return {zeroReviewsText:m?m[0]:null,anyReviewMention:any?any[0]:null}});
R.c8_payment_pdp=await p.evaluate(()=>({payWords:/visa|mastercard|paypal|klarna|apple pay|google pay/i.test(document.body.innerText),imgs:[...document.querySelectorAll('img[alt*="pay" i],img[alt*="visa" i],img[alt*="klarna" i]')].length}));
// 3) COLLECTION sold-out
await p.goto('https://selvaro.de/collections/all',{waitUntil:'domcontentloaded',timeout:45000}); await sleep(3500);
R.c4_collection=await p.evaluate(async()=>{const sl=ms=>new Promise(r=>setTimeout(r,ms));for(let y=0;y<=4000;y+=400){scrollTo(0,y);await sl(90)}await sl(800);const t=document.body.innerText;const cards=[...document.querySelectorAll('a[href*="/products/"]')];const handles=[...new Set(cards.map(a=>(a.getAttribute('href').match(/\/products\/([a-z0-9-]+)/)||[])[1]).filter(Boolean))];return {soldOutWords:(t.match(/ausverkauft|sold out|nicht verfügbar|vergriffen/gi)||[]).length,productLinks:handles.length,handles:handles.slice(0,15)}});
// 4) products.json availability (fresh)
const pj=await p.evaluate(async()=>{const r=await fetch('/products.json?limit=250');const j=await r.json();return j.products.map(p=>({h:p.handle,t:p.title,av:p.variants.some(v=>v.available),vars:p.variants.length}))});
R.c4_products={total:pj.length,unavailable:pj.filter(x=>!x.av).length,list:pj.map(x=>({h:x.h,av:x.av}))};
// 5) CART with item
const vid=await p.evaluate(async()=>{const r=await fetch('/products/lernturm-klappbar.js');const j=await r.json();const v=j.variants.find(v=>v.available)||j.variants[0];return v.id});
await p.goto('https://selvaro.de/cart/add?id='+vid+'&quantity=1',{waitUntil:'domcontentloaded',timeout:45000}); await sleep(2000);
await p.goto('https://selvaro.de/cart',{waitUntil:'domcontentloaded',timeout:45000}); await sleep(3500);
R.c5_cart=await p.evaluate(()=>{const t=document.body.innerText;return {freeShipProgress:/noch\s*[\d.,]+\s*€|kostenlos(er|em)?\s*versand/i.test(t),progressEl:!!document.querySelector('[class*="progress"],[class*="shipping-bar"],[class*="threshold"],[class*="free-ship"]'),text:t.replace(/\s+/g,' ').slice(0,420),express:/shop pay|paypal|google pay|apple pay/i.test(t),promo:!!document.querySelector('input[name="discount"],[class*="discount-code"]'),upsell:!!document.querySelector('[class*="recommend"],[class*="upsell"],[class*="also-like"]')}});
fs.writeFileSync('_build/qa_live.json',JSON.stringify(R,null,1)); console.log(JSON.stringify(R,null,1).slice(0,4500)); await b.close(); process.exit(0);
})().catch(e=>{fs.writeFileSync('_build/qa_live.json',JSON.stringify({...R,fatal:String(e)},null,1));console.error('ERR',e);process.exit(1)});
